import 'minifill/src/Array.from.js'
import 'minifill/src/Element.prototype.matches.js'
import 'minifill/src/Element.prototype.closest.js'
import 'minifill/src/Multi.Event.js'
import 'minifill/src/Multi.CustomEvent.js'
import 'minifill/src/Node.prototype.contains.js'