export default BSN;
declare namespace BSN {
    export { Alert };
    export { Button };
    export { Carousel };
    export { Collapse };
    export { Dropdown };
    export { Modal };
    export { Offcanvas };
    export { Popover };
    export { ScrollSpy };
    export { Tab };
    export { Toast };
    export { Tooltip };
    export { initCallback };
    export { Version };
}
import Alert from "./components/alert-native.js";
import Button from "./components/button-native.js";
import Carousel from "./components/carousel-native.js";
import Collapse from "./components/collapse-native.js";
import Dropdown from "./components/dropdown-native.js";
import Modal from "./components/modal-native.js";
import Offcanvas from "./components/offcanvas-native.js";
import Popover from "./components/popover-native.js";
import ScrollSpy from "./components/scrollspy-native.js";
import Tab from "./components/tab-native.js";
import Toast from "./components/toast-native.js";
import Tooltip from "./components/tooltip-native.js";
import { initCallback } from "./util/init.js";
import Version from "./util/version.js";
